name: yift
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0

  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.0
  email_validator: ^2.1.17
  timeago: ^3.4.0
  intl: ^0.17.0
  package_info_plus: ^3.0.3

  dio: ^5.0.3
  http: ^0.13.5
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5

  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4

  google_sign_in: ^6.0.2
  flutter_facebook_auth: "^5.0.8"
  kakao_flutter_sdk_user: ^1.4.2
  sign_in_with_apple: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
