// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8obtYeItLrjCyA2tO_xHoMnexZ5Infdw',
    appId: '1:761270360924:web:0617588fa61913f9887f99',
    messagingSenderId: '761270360924',
    projectId: 'you-in-factasy',
    authDomain: 'you-in-factasy.firebaseapp.com',
    storageBucket: 'you-in-factasy.appspot.com',
    measurementId: 'G-MY45C541RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9UytuH3DNvWTMKTh3ApBYZjeMeGPu3zM',
    appId: '1:761270360924:android:df1561c961db72f7887f99',
    messagingSenderId: '761270360924',
    projectId: 'you-in-factasy',
    storageBucket: 'you-in-factasy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqxJjqybgsshrMBM0HkQjiZiefo3efPs',
    appId: '1:761270360924:ios:b0088f40cecaaa8b887f99',
    messagingSenderId: '761270360924',
    projectId: 'you-in-factasy',
    storageBucket: 'you-in-factasy.appspot.com',
    iosClientId: '761270360924-8p1dq3665m3qjcj6mm8nac7lqsdt6d1r.apps.googleusercontent.com',
    iosBundleId: 'com.hj.yift',
  );
}
